# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcproto/executor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpcproto/executor.proto\x12\x0e\x65xecutorinfran\"\xba\x01\n\x12IdentifyOneRequest\x12\r\n\x05TrxID\x18\x01 \x01(\t\x12\x10\n\x08TenantID\x18\x02 \x01(\t\x12\x11\n\tTimestamp\x18\x03 \x01(\t\x12\x10\n\x08\x44\x65viceID\x18\x04 \x01(\t\x12\x13\n\x0b\x45mbeddingID\x18\x05 \x01(\t\x12\x18\n\x10\x45mbeddingFeature\x18\x06 \x03(\x02\x12\x16\n\x0e\x45mbeddingBytes\x18\x07 \x01(\x0c\x12\x17\n\x0f\x45mbeddingString\x18\x08 \x03(\t\"\xc1\x01\n\x13IdentifyOneResponse\x12\r\n\x05TrxID\x18\x01 \x01(\t\x12\x0e\n\x06Result\x18\x02 \x01(\t\x12\x0e\n\x06Status\x18\x03 \x01(\t\x12\x0f\n\x07\x45rrCode\x18\x04 \x01(\t\x12\x13\n\x0b\x45mbeddingID\x18\x05 \x01(\t\x12\x18\n\x10MatchEmbeddingID\x18\x06 \x01(\t\x12\x17\n\x0f\x43onfidenceScore\x18\x07 \x01(\x02\x12\x0f\n\x07Message\x18\x08 \x01(\t\x12\x11\n\tTimestamp\x18\t \x01(\t2p\n\x14\x45xecutorInfranFaceID\x12X\n\x0bIdentifyOne\x12\".executorinfran.IdentifyOneRequest\x1a#.executorinfran.IdentifyOneResponse\"\x00\x42\x43\n\x1eio.infran.executorinfranfaceidB\x19\x45xecutorInfranFaceIDProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcproto.executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036io.infran.executorinfranfaceidB\031ExecutorInfranFaceIDProtoP\001\242\002\003RTG'
  _globals['_IDENTIFYONEREQUEST']._serialized_start=45
  _globals['_IDENTIFYONEREQUEST']._serialized_end=231
  _globals['_IDENTIFYONERESPONSE']._serialized_start=234
  _globals['_IDENTIFYONERESPONSE']._serialized_end=427
  _globals['_EXECUTORINFRANFACEID']._serialized_start=429
  _globals['_EXECUTORINFRANFACEID']._serialized_end=541
# @@protoc_insertion_point(module_scope)
