# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpcproto import executor_pb2 as grpcproto_dot_executor__pb2


class ExecutorInfranFaceIDStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IdentifyOne = channel.unary_unary(
                '/executorinfran.ExecutorInfranFaceID/IdentifyOne',
                request_serializer=grpcproto_dot_executor__pb2.IdentifyOneRequest.SerializeToString,
                response_deserializer=grpcproto_dot_executor__pb2.IdentifyOneResponse.FromString,
                )


class ExecutorInfranFaceIDServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IdentifyOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorInfranFaceIDServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IdentifyOne': grpc.unary_unary_rpc_method_handler(
                    servicer.IdentifyOne,
                    request_deserializer=grpcproto_dot_executor__pb2.IdentifyOneRequest.FromString,
                    response_serializer=grpcproto_dot_executor__pb2.IdentifyOneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executorinfran.ExecutorInfranFaceID', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExecutorInfranFaceID(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IdentifyOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/executorinfran.ExecutorInfranFaceID/IdentifyOne',
            grpcproto_dot_executor__pb2.IdentifyOneRequest.SerializeToString,
            grpcproto_dot_executor__pb2.IdentifyOneResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
